"""Add likes_count to Cafe model

Revision ID: 00d4416c69bd
Revises: 75858a2593f8
Create Date: 2025-11-25 23:17:10.518434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d4416c69bd'
down_revision = '75858a2593f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
