"""Update cafe model

Revision ID: 0b8804b00015
Revises: 
Create Date: 2025-10-12 16:48:29.533118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8804b00015'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_consents', sa.Integer(), nullable=True))
        batch_op.alter_column('hours_weekday',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('hours_weekend',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('monday',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('tuesday',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('wednesday',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('thursday',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('friday',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('saturday',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('sunday',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('reservation_start_time',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('reservation_end_time',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('max_advance_days')
        batch_op.drop_column('min_advance_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_advance_hours', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('max_advance_days', sa.INTEGER(), nullable=True))
        batch_op.alter_column('reservation_end_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('reservation_start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('sunday',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('saturday',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('friday',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('thursday',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('wednesday',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('tuesday',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('monday',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('hours_weekend',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('hours_weekday',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('total_consents')

    # ### end Alembic commands ###
