"""empty message

Revision ID: 1de963583c09
Revises: 91ed2c30d5d9
Create Date: 2025-11-24 22:56:43.250101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1de963583c09'
down_revision = '91ed2c30d5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe_time_slots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_time_slots',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cafe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time_slot', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('total_seats', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_seats', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserved_seats', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], name='cafe_time_slots_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cafe_time_slots', schema=None) as batch_op:
        batch_op.create_index('uq_cafe_date_time', ['cafe_id', 'date', 'time_slot'], unique=True)

    # ### end Alembic commands ###
