"""update cafe model - 운영시간

Revision ID: 3580ae34680d
Revises: 0b8804b00015
Create Date: 2025-10-12 16:59:28.141799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3580ae34680d'
down_revision = '0b8804b00015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday_begin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('monday_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_begin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_begin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('thursday_begin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('thursday_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('friday_begin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('friday_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('saturday_begin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('saturday_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sunday_begin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sunday_end', sa.DateTime(), nullable=True))
        batch_op.drop_column('saturday')
        batch_op.drop_column('sunday')
        batch_op.drop_column('tuesday')
        batch_op.drop_column('monday')
        batch_op.drop_column('wednesday')
        batch_op.drop_column('thursday')
        batch_op.drop_column('friday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friday', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('thursday', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('wednesday', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('monday', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('tuesday', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sunday', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('saturday', sa.DATETIME(), nullable=True))
        batch_op.drop_column('sunday_end')
        batch_op.drop_column('sunday_begin')
        batch_op.drop_column('saturday_end')
        batch_op.drop_column('saturday_begin')
        batch_op.drop_column('friday_end')
        batch_op.drop_column('friday_begin')
        batch_op.drop_column('thursday_end')
        batch_op.drop_column('thursday_begin')
        batch_op.drop_column('wednesday_end')
        batch_op.drop_column('wednesday_begin')
        batch_op.drop_column('tuesday_end')
        batch_op.drop_column('tuesday_begin')
        batch_op.drop_column('monday_end')
        batch_op.drop_column('monday_begin')

    # ### end Alembic commands ###
