"""empty message

Revision ID: 489266cb6fe1
Revises: 6d8c50a88ac1
Create Date: 2025-11-09 21:03:05.205068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '489266cb6fe1'
down_revision = '6d8c50a88ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
