"""empty message

Revision ID: 57a9516dc762
Revises: 54979d80b343
Create Date: 2026-02-01 14:09:19.800568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57a9516dc762'
down_revision = '54979d80b343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seat_rate', sa.Integer(), nullable=True))
        batch_op.alter_column('rate',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe_ratings', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('seat_rate')
        batch_op.drop_column('consent_rate')

    # ### end Alembic commands ###
