"""user nickname 추가

Revision ID: 6809fd373044
Revises: 489266cb6fe1
Create Date: 2025-11-18 20:27:04.488110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6809fd373044'
down_revision = '489266cb6fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
