"""Change time cols to string type

Revision ID: 6cb9101a9812
Revises: 3580ae34680d
Create Date: 2025-10-12 17:55:24.492463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb9101a9812'
down_revision = '3580ae34680d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.alter_column('monday_begin',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('monday_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('tuesday_begin',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('tuesday_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('wednesday_begin',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('wednesday_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('thursday_begin',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('thursday_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('friday_begin',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('friday_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('saturday_begin',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('saturday_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('sunday_begin',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('sunday_end',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('reservation_start_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('reservation_end_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.alter_column('reservation_end_time',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('reservation_start_time',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('sunday_end',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('sunday_begin',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('saturday_end',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('saturday_begin',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('friday_end',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('friday_begin',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('thursday_end',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('thursday_begin',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('wednesday_end',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('wednesday_begin',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('tuesday_end',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('tuesday_begin',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('monday_end',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('monday_begin',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
