"""Initial MySQL schema

Revision ID: 6d8c50a88ac1
Revises: 
Create Date: 2025-10-26 16:35:14.905892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8c50a88ac1'
down_revision = None
branch_labels = None
depends_on = None
###################################################

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('hours_weekday', sa.Integer(), nullable=True),
    sa.Column('hours_weekend', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('last_order', sa.String(length=50), nullable=True),
    sa.Column('monday_begin', sa.String(length=5), nullable=True),
    sa.Column('monday_end', sa.String(length=5), nullable=True),
    sa.Column('tuesday_begin', sa.String(length=5), nullable=True),
    sa.Column('tuesday_end', sa.String(length=5), nullable=True),
    sa.Column('wednesday_begin', sa.String(length=5), nullable=True),
    sa.Column('wednesday_end', sa.String(length=5), nullable=True),
    sa.Column('thursday_begin', sa.String(length=5), nullable=True),
    sa.Column('thursday_end', sa.String(length=5), nullable=True),
    sa.Column('friday_begin', sa.String(length=5), nullable=True),
    sa.Column('friday_end', sa.String(length=5), nullable=True),
    sa.Column('saturday_begin', sa.String(length=5), nullable=True),
    sa.Column('saturday_end', sa.String(length=5), nullable=True),
    sa.Column('sunday_begin', sa.String(length=5), nullable=True),
    sa.Column('sunday_end', sa.String(length=5), nullable=True),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('reservation_enabled', sa.Boolean(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('total_consents', sa.Integer(), nullable=True),
    sa.Column('reservation_start_time', sa.String(length=5), nullable=True),
    sa.Column('reservation_end_time', sa.String(length=5), nullable=True),
    sa.Column('hourly_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('cafe_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=5), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('reserved_seats', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cafe_id', 'date', 'time_slot', name='uq_cafe_date_time')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('order_name', sa.String(length=100), nullable=False),
    sa.Column('payment_key', sa.String(length=200), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('payment_key')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('orders')
    op.drop_table('cafe_time_slots')
    op.drop_table('users')
    op.drop_table('cafes')
    # ### end Alembic commands ###
