"""Add cafe_likes table

Revision ID: 75858a2593f8
Revises: 1de963583c09
Create Date: 2025-11-25 14:32:30.413897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75858a2593f8'
down_revision = '1de963583c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cafe_id', name='unique_user_cafe_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe_likes')
    # ### end Alembic commands ###
