"""empty message

Revision ID: 91ed2c30d5d9
Revises: 40fce4911910
Create Date: 2025-11-23 16:44:56.436942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ed2c30d5d9'
down_revision = '40fce4911910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_key', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('payment_key')

    # ### end Alembic commands ###
