// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkFY0MOnF06aGS56yRMbGgzB5GAIU--NY',
    appId: '1:447275815920:web:5d627008c64d70a47ac335',
    messagingSenderId: '447275815920',
    projectId: 'cagonginfo',
    authDomain: 'cagonginfo.firebaseapp.com',
    storageBucket: 'cagonginfo.appspot.com',
    measurementId: 'G-V0F7G0YCCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABolZAxsqvzWXVsg0RO-DPoemF-1SOY0M',
    appId: '1:447275815920:android:35e2fa445b228ee97ac335',
    messagingSenderId: '447275815920',
    projectId: 'cagonginfo',
    storageBucket: 'cagonginfo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwIFtLpbe0iv24r4iANc6MBD8gHcEeRMY',
    appId: '1:447275815920:ios:3a737508bdba2a0f7ac335',
    messagingSenderId: '447275815920',
    projectId: 'cagonginfo',
    storageBucket: 'cagonginfo.appspot.com',
    iosBundleId: 'com.example.cagongGooglemap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwIFtLpbe0iv24r4iANc6MBD8gHcEeRMY',
    appId: '1:447275815920:ios:3a737508bdba2a0f7ac335',
    messagingSenderId: '447275815920',
    projectId: 'cagonginfo',
    storageBucket: 'cagonginfo.appspot.com',
    iosBundleId: 'com.example.cagongGooglemap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkFY0MOnF06aGS56yRMbGgzB5GAIU--NY',
    appId: '1:447275815920:web:a7e8a6c781f39f7e7ac335',
    messagingSenderId: '447275815920',
    projectId: 'cagonginfo',
    authDomain: 'cagonginfo.firebaseapp.com',
    storageBucket: 'cagonginfo.appspot.com',
    measurementId: 'G-QBWC48Q8B3',
  );
}
